export default class Types {
  /** COUNTRY DATA **/
  static SET_COUNTRY_DATA_PROPS = 'SET_COUNTRY_DATA_PROPS'

  /** CLEAR DATA */
  static CLEAR_ERROR_COUNTRY_DATA = 'CLEAR_ERROR_COUNTRY_DATA'
  static CLEAR_COUNTRY_DATA = 'CLEAR_COUNTRY_DATA'
}
