export default class Types {
  static SET_ADMIN_LOGIN_STATE = 'SET_ADMIN_LOGIN_STATE'
  static SET_VALUE_POST_DATA_ADMIN_LOGIN = 'SET_VALUE_POST_DATA_ADMIN_LOGIN'
  static CLEAR_ADMIN_LOGIN_DATA = 'CLEAR_ADMIN_LOGIN_DATA'
  static CLEAR_ADMIN_LOGIN_DATA_ERROR = 'CLEAR_ADMIN_LOGIN_DATA_ERROR'
}
