export default class Types {
  /** SUPPLIER DATA **/
  static SET_SUPPLIER_DATA_PROPS = 'SET_SUPPLIER_DATA_PROPS'
  static SET_VALUE_SUPPLIER_FILTERS_DATA = 'SET_VALUE_SUPPLIER_FILTERS_DATA'
  static SET_VALUE_SUPPLIER_PAYMENT_PREFERENCES_DATA = 'SET_VALUE_SUPPLIER_PAYMENT_PREFERENCES_DATA'

  /** CLEAR DATA */
  static CLEAR_ERROR_SUPPLIER_DATA = 'CLEAR_ERROR_SUPPLIER_DATA'
  static CLEAR_SUPPLIER_DATA = 'CLEAR_SUPPLIER_DATA'
  static CLEAR_SUPPLIERS_DATA = 'CLEAR_SUPPLIERS_DATA'
  static CLEAR_SUPPLIER_FILTERS = 'CLEAR_SUPPLIER_FILTERS'

  /** GET DATA */
  static GET_SUPPLIER = 'GET_SUPPLIER'
}
