export default class Types {
  static SET_ONBOARDING_PROFILE_DATA_PROPS = 'SET_ONBOARDING_PROFILE_DATA_PROPS'
  static CLEAR_TO_INITIAL_STATE = 'CLEAR_TO_INITIAL_STATE'
  static CLEAR_ERROR_ONBOARDING_PROFILES_DATA = 'CLEAR_ERROR_ONBOARDING_PROFILES_DATA'
  static CLEAR_ONBOARDING_PROFILES_DATA = 'CLEAR_ONBOARDING_PROFILES_DATA'
  static CLEAR_ONBOARDING_PROFILE_DATA = 'CLEAR_ONBOARDING_PROFILE_DATA'
}
