export enum Tags {
    POST_USER_COMPANY = 'POST_USER_COMPANY',
    PUT_USER_COMPANY = 'PUT_USER_COMPANY',
    GET_USERS_COMPANY = 'GET_USERS_COMPANY',
    GET_USER_COMPANY_BY_ID = 'GET_USER_COMPANY_BY_ID',
    DEL_USER_COMPANY = 'DEL_USER_COMPANY'
}
