export default class Types {
  /** CLEAR DATA DASHBOARD */
  static CLEAR_DATA_DASHBOARD = 'CLEAR_DATA_DASHBOARD'

  /** GET DATA */
  static GET_DASHBOARD_METRICS_SUCCESS = 'GET_DASHBOARD_METRICS_SUCCESS'
  static GET_DASHBOARD_METRICS_FAIL = 'GET_DASHBOARD_METRICS_FAIL'

  /** SET DATA DASHBOARD **/
  static SET_DASHBOARD_STATE = 'SET_DASHBOARD_STATE'
}
