export default class Types {
  /** INVOICE DATA **/
  static SET_INVOICE_DATA_PROPS = 'SET_INVOICE_DATA_PROPS'
  static SET_VALUE_POST_INVOICE_DATA = 'SET_VALUE_POST_INVOICE_DATA'
  static SET_VALUE_POST_CUSTOMER_INVOICE_DATA = 'SET_VALUE_POST_CUSTOMER_INVOICE_DATA'
  static SET_VALUE_CURRENCY_DATA = 'SET_VALUE_CURRENCY_DATA'
  static SET_VALUE_INVOICES_FILTERS_DATA = 'SET_VALUE_INVOICE_FILTERS_DATA'
  static SET_SEND_MESSAGE = 'SET_SEND_MESSAGE'
  static SET_IS_MARK_AS_PAID = 'SET_IS_MARK_AS_PAID'
  static SET_PAID_TO_FINANCIAL = 'SET_PAID_TO_FINANCIAL'

  /** GET DATA */
  static GET_INVOICE = 'GET_INVOICE'
  static GET_CURRENCY = 'GET_CURRENCY'

  /** CLEAR DATA */
  static CLEAR_TO_INITIAL_STATE = 'CLEAR_TO_INITIAL_STATE'
  static CLEAR_INVOICES_PAGINATION = 'CLEAR_INVOICES_PAGINATION'
  static CLEAR_ERROR_INVOICES_DATA = 'CLEAR_ERROR_INVOICES_DATA'
  static CLEAR_ERROR_INVOICE_DATA = 'CLEAR_ERROR_INVOICE_DATA'
  static CLEAR_ERROR_INVOICE_DATA_FOR_ADD = 'CLEAR_ERROR_INVOICE_DATA_FOR_ADD'
  static CLEAR_ERROR_EMAILS_DATA = 'CLEAR_ERROR_EMAILS_DATA'
  static CLEAR_INVOICE_DATA = 'CLEAR_INVOICE_DATA'
  static CLEAR_INVOICE_LOADINGS = 'CLEAR_INVOICE_LOADINGS'
  static CLEAR_INVOICES_DATA = 'CLEAR_INVOICES_DATA'
  static CLEAR_INVOICES_FILTERS = 'CLEAR_INVOICES_FILTERS'
}
