export default class Types {
  /** INVOICE DATA **/
  static SET_RECEIVED_INVOICE_DATA_PROPS = 'SET_RECEIVED_INVOICE_DATA_PROPS'
  static SET_RECEIVED_QUICKPAY_INVOICE_DATA_PROPS = 'SET_RECEIVED_QUICKPAY_INVOICE_DATA_PROPS'
  static SET_VALUE_CURRENCY_DATA = 'SET_VALUE_CURRENCY_DATA'

  /** GET DATA */
  static GET_CURRENCY = 'GET_CURRENCY'

  /** CLEAR DATA */
  static CLEAR_ERROR_RECEIVED_INVOICES_DATA = 'CLEAR_ERROR_RECEIVED_INVOICES_DATA'
  static CLEAR_RECEIVED_INVOICES_DATA = 'CLEAR_RECEIVED_INVOICES_DATA'
  static CLEAR_TO_INITIAL_STATE = 'CLEAR_TO_INITIAL_STATE'
  static CLEAR_RECEIVED_INVOICES_PAGINATION = 'CLEAR_RECEIVED_INVOICES_PAGINATION'
}
