export default class Types {
  /** USER ACCESS TOKEN **/
  static SET_USER_ACCESS_TOKEN = 'SET_USER_ACCESS_TOKEN'

  /** USER DATA **/
  static SET_USER_DATA_PROPS = 'SET_USER_DATA_PROPS'
  static SET_VALUE_POST_DATA_USER = 'SET_VALUE_POST_DATA_USER'
  static SET_VALUE_POST_DATA_USER_COMPANY = 'SET_VALUE_POST_DATA_USER_COMPANY'
  static SET_VALUE_PUT_DATA_USER = 'SET_VALUE_PUT_DATA_USER'
  static SET_VALUE_CHANGE_EMAIL = 'SET_VALUE_CHANGE_EMAIL'
  static SET_USER_COMPANY_BRANCH_SELECTED = 'SET_USER_COMPANY_BRANCH_SELECTED'

  /** USER LOGOUT **/
  static SET_USER_LOGOUT = 'SET_USER_LOGOUT'

  /** SUCCESS SUPPLIER ME */
  static SET_SUCCESS_SUPPLIER_ME = 'SET_SUCCESS_SUPPLIER_ME'

  /** CLEAR DATA */
  static CLEAR_ERROR_USER_DATA = 'CLEAR_ERROR_USER_DATA'
  static CLEAR_USER_ACCESS_TOKEN = 'CLEAR_USER_ACCESS_TOKEN'
  static CLEAR_USER_DATA = 'CLEAR_USER_DATA'
  static CLEAR_POST_DATA_USER = 'CLEAR_POST_DATA_USER'
  static CLEAR_ERROR_USER_DATA_PUT = 'CLEAR_ERROR_USER_DATA_PUT'
  static CLEAR_CHANGE_EMAIL_DATA = 'CLEAR_CHANGE_EMAIL_DATA'
}
