export enum Tags {
    DEL_USER = 'DEL_USER',
    GET_USER_ME = 'GET_USER_ME',
    PUT_USER = 'PUT_USER',
    PUT_USER_TYPE ='PUT_USER_TYPE',
    POST_EXTERNAL_PAYMENT = 'POST_EXTERNAL_PAYMENT',
    PATCH_PAYMENT_PREFERENCES = 'PATCH_PAYMENT_PREFERENCES'
}
