export enum Tags {
    GET_MY_SUPPLIERS = 'GET_MY_SUPPLIERS',
    GET_SUPPLIER_PAYMENT_PREFERENCES = 'GET_SUPPLIER_PAYMENT_PREFERENCES',
    PATCH_SUPPLIER_PAYMENT_PREFERENCES = 'PATCH_SUPPLIER_PAYMENT_PREFERENCES',
}
