export default class Types {
  /** UPDATE STATE */
  static SET_LOGIN_STATE = 'SET_LOGIN_STATE'
  static SET_VALUE_POST_DATA_LOGIN = 'SET_VALUE_POST_DATA_LOGIN'

  /** CLEAR STATE */
  static CLEAR_LOGIN_DATA = 'CLEAR_LOGIN_DATA'
  static CLEAR_LOGIN_DATA_ERROR = 'CLEAR_LOGIN_DATA_ERROR'
}
