export default class Types {
  static SET_USER_COMPANY_DATA_PROPS = 'SET_USER_COMPANY_DATA_PROPS'
  static SET_VALUE_POST_USER_COMPANY = 'SET_VALUE_POST_USER_COMPANY'
  static CLEAR_POST_DATA_USER_COMPANY = 'CLEAR_POST_DATA_USER_COMPANY'
  static CLEAR_ERROR_POST_USER_COMPANY = 'CLEAR_ERROR_POST_USER_COMPANY'
  static SET_VALUE_PUT_USER_COMPANY = 'SET_VALUE_PUT_USER_COMPANY'
  static SET_VALUE_PUT_USER_DATA = 'SET_VALUE_PUT_USER_DATA'
  static SET_VALUE_PUT_COMPANY_DATA = 'SET_VALUE_PUT_COMPANY_DATA'
  static CLEAR_PUT_DATA_USER_COMPANY = 'CLEAR_PUT_DATA_USER_COMPANY'
  static CLEAR_ERROR_PUT_USER_COMPANY = 'CLEAR_ERROR_PUT_USER_COMPANY'
  static CLEAR_USER_COMPANY_DATA = 'CLEAR_USER_COMPANY_DATA'
}
