export enum Tags {
    DEL_COMPANY_TAX = 'DEL_COMPANY_TAX',
    GET_DEFAULT_TAXES = 'GET_DEFAULT_TAXES',
    GET_COMPANY_TAXES = 'GET_COMPANY_TAXES',
    GET_COMPANY_TAX = 'GET_COMPANY_TAX',
    POST_COMPANY_TAX = 'POST_COMPANY_TAX',
    PUT_COMPANY_TAX = 'PUT_COMPANY_TAX'
}
