export default class Types {
  static SET_ADMIN_USER_ACCESS_TOKEN = 'SET_ADMIN_USER_ACCESS_TOKEN'
  static SET_ADMIN_USER_DATA_PROPS = 'SET_ADMIN_USER_DATA_PROPS'
  static SET_ADMIN_USER_LOGOUT = 'SET_ADMIN_USER_LOGOUT'
  static CLEAR_ADMIN_USER_ACCESS_TOKEN = 'CLEAR_ADMIN_USER_ACCESS_TOKEN'
}
