export default class Types {
  /** CLIENT DATA **/
  static SET_CLIENT_DATA_PROPS = 'SET_CLIENT_DATA_PROPS'
  static SET_CLIENT_INVOICES_DATA_PROPS = 'SET_CLIENT_INVOICES_DATA_PROPS'
  static SET_CLIENT_NEW_BRANCH_PROPS = 'SET_CLIENT_NEW_BRANCH_PROPS'
  static SET_VALUE_POST_CLIENT_DATA = 'SET_VALUE_POST_CLIENT_DATA'
  static SET_VALUE_POST_CLIENT_COMPANY_DATA = 'SET_VALUE_POST_CLIENT_COMPANY_DATA'
  static SET_VALUE_PUT_CLIENT_DATA = 'SET_VALUE_PUT_CLIENT_DATA'
  static SET_VALUE_CLIENT_FILTERS_DATA = 'SET_VALUE_CLIENT_FILTERS_DATA'
  static SET_SEARCH_CLIENT = 'SET_SEARCH_CLIENT'
  static SET_SELECTED_SUPPLIER = 'SET_SELECTED_SUPPLIER'
  static SET_PAYMENT_PREFERENCES = 'SET_PAYMENT_PREFERENCES'
  static SET_PAYMENT_PREFERENCES_EXTERNAL = 'SET_PAYMENT_PREFERENCES_EXTERNAL'
  static SET_FINANCIAL_COMPANY = 'SET_FINANCIAL_COMPANY'
  static SET_SHOW_SUPPLIER = 'SET_SHOW_SUPPLIER'
  static SET_FINANCIAL_EXISTS_RELATED_TO_CLIENT = 'SET_FINANCIAL_EXISTS_RELATED_TO_CLIENT'
  
  /** CLEAR DATA */
  static CLEAR_ERROR_CLIENT_DATA = 'CLEAR_ERROR_CLIENT_DATA'
  static CLEAR_CLIENT_DATA = 'CLEAR_CLIENT_DATA'
  static CLEAR_CLIENTS_DATA = 'CLEAR_CLIENTS_DATA'
  static CLEAR_CLIENT_FILTERS = 'CLEAR_CLIENT_FILTERS'

  /** GET DATA */
  static GET_SUPPLIER_CLIENTS = 'GET_SUPPLIER_CLIENTS'
  static GET_CLIENTS_BY_CIF = 'GET_CLIENTS_BY_CIF'
  static GET_USERS_COMPANY = 'GET_USERS_COMPANY'
  static SET_CLIENT_SELECTED_BY_CIF = 'SET_CLIENT_SELECTED_BY_CIF'
  static SET_FINANCIAL_SELECTED_BY_CIF = 'SET_FINANCIAL_SELECTED_BY_CIF'
  static SET_CUSTOMER_SELECTED_BY_CIF = 'SET_CUSTOMER_SELECTED_BY_CIF'
  static GET_SUPPLIER_CLIENTS_WITH_INVOICES = 'GET_SUPPLIER_CLIENTS_WITH_INVOICES'
  static GET_CLIENT = 'GET_CLIENT'
  static GET_COUNTRIES = 'GET_COUNTRIES'
}
