export default class Types {
  static SET_MY_COMPANIES_DATA_PROPS = 'SET_MY_COMPANIES_DATA_PROPS'
  static SET_INVOICE_PROPS = 'SET_INVOICE_PROPS'
  static CLEAR_COMPANIES_DATA = 'CLEAR_COMPANIES_DATA'
}
